[package]
name = "splein"
version = "0.0.1-rc.1"
edition = "2021"
publish = true
description = "Draw screen overlay"
license = "GPL-3.0"

[dependencies]
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
tracing-error = { workspace = true }
tracing-flame = { workspace = true }
typed-builder = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
smithay-client-toolkit = { workspace = true }
tiny-skia = { workspace = true }
wayland-client = { workspace = true }
wayland-protocols-wlr = { workspace = true }
calloop = { workspace = true }
taffy = { workspace = true }
cosmic-text = { workspace = true }
